#:schema node_modules/wrangler/config-schema.json
name = "redirect"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
minify = true

[observability.logs]
enabled = false # Free plan is NOT that generous :)

