name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  APP_NAME: "acikgozb-dev"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
  FRONTEND_ARTIFACT_PATH: "public"

jobs:
  create-frontend-assets:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install `hugo`
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.139.3

      - name: Create frontend artifact
        shell: bash
        run: |
          hugo build --destination "$FRONTEND_ARTIFACT_PATH" --minify

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: "${{ env.FRONTEND_ARTIFACT_PATH }}"

  deploy:
    runs-on: ubuntu-24.04
    needs: create-frontend-assets

    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ env.AWS_REGION }}"
          role-to-assume: "${{ secrets.AWS_OIDC_ROLE_ARN }}"
          role-session-name: "${{ env.APP_NAME }}-aws-session-${{ github.run_id }}"

      - name: Set environment
        run: |
          read -r -a tf_env < <(./scripts/exec environment); \
          for env in ${tf_env[@]}; \
          do \
            echo "${env%:*}=${env#*:}" >> "$GITHUB_ENV"; \
          done

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Initialize Terraform
        run: |
          ./scripts/exec init

      - name: Download frontend artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: "${{ env.FRONTEND_ARTIFACT_PATH}}"

      - name: Debug the workdir
        run: |
          ls -R

    # - name: Create Terraform plan
    #   run: |
    #     ./scripts/exec plan
    #
    # - name: Apply Terraform plan
    #   run: |
    #     ./scripts/exec apply > /dev/null
